# This is a configuration for a debug build primarily used with docker compose.
# Since docker compose sets up a platform container as if it were a production-configured
# deployment, there's a few things we need for local development (such as a local mailbox) hence
# the debug build.
import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :platform, PlatformWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"
config :platform, dev_routes: true

# Do not print debug messages in production
config :logger, level: :debug

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
