import Config

# Configure your database
config :platform, Platform.Repo,
  url: "postgres://platform:localdev@localhost:5432/platform",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :platform, PlatformWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  # Dev-only throwaway key. Generate your own with: mix phx.gen.secret
  secret_key_base: "VZ05raqS7ythc5tkdlmSU5xcxQ5fYCs361mZDtd8kFOYgFKFB5s4G26CYX6unC16",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:platform, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:platform, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :platform, PlatformWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/platform_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :platform, dev_routes: true

# Include human-readable local timestamps in development logs
config :logger, utc_log: false
config :logger, :default_formatter, format: "$date $time [$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

config :platform, Platform.StorageBucket,
  bucket: "localdev",
  location_prefix: "public/uploads"

config :ex_aws, :s3,
  scheme: "http://",
  host: "localhost",
  port: 9000

config :ex_aws,
  access_key_id: "minioadmin",
  secret_access_key: "minioadmin"

config :platform, Platform.PDFAgent,
  invoice_url: "http://localhost:8000/invoice",
  w2_url: "http://localhost:8000/w2",
  receipt_url: "http://localhost:8000/receipt",
  nec1099_url: "http://localhost:8000/1099-nec",
  bank_statement_url: "http://localhost:8000/bank-statement"
